### ISSUE TITLE
Typing zero into the date field cleared the whole page

### ISSUE THREAD

**Issue by ezagroba** [coderbyheart/localschedule#10]
I tabbed to the date field. I started to type `03` for March, mirroring the `02` that was already there, and discovered the whole page turned white as soon as I typed `0`. See attached screen capture. 

Browser: Brave 1.20.103
OS: Mac 10.13.6

https://user-images.githubusercontent.com/1462795/109385131-da4f1780-78f1-11eb-9126-094ef14c0678.mov

**Comment by coderbyheart** [comment]
Thank you, perfect bug report!

I handle partially entered dates badly. Will fix this weekend!

**Comment by coderbyheart** [comment]
Workaround: the date field should show a date picker, using that will result in valid dates being entered in the input field.

![image](https://user-images.githubusercontent.com/188915/109386728-01f7ad00-78fd-11eb-9e43-27f0df7b05dd.png)

**Comment by ezagroba** [comment]
Thanks Markus! The black date picker icon wasn't visible in the dark theme, but I was able to tab to the field and up/down arrow from there.

**Comment by coderbyheart** [comment]
Right, same issue here on Chrome.
Will look into fixing this, too. See #11.
