### ISSUE TITLE
App returns to home page without saving when adding a session on Firefox desktop

### ISSUE THREAD

**Issue by j19sch** [coderbyheart/localschedule#108]
On Firefox 119.0 (Ubuntu, snap package canonical-002 - 1.0) when I add a session by either clicking the green + or hitting "Enter", the home page is loaded and the session I tried to add is not 'saved'. It's not reproducible 100% of the time, but very close to it.

The behavior also occurs on Firefox for Mac. It does not:
- on Google Chrome (Ubuntu)
- on Firefox for Android
- by running the e2e tests with Firefox (after updating the test to add two sessions)

We've seen this behavior for the first time in October or November, so presumable it's not an issue with just one specific version of Firefox.

Sorry for dropping such a tricky issue on your doorstep.

**Comment by coderbyheart** [comment]
Thanks for the report. Will look into it in the next weeks.

**Comment by coderbyheart** [comment]
Could you share the error log from the console when you reproduce it?

**Comment by coderbyheart** [comment]
Tested on OS X 14.2 and Firefox 121 and could add multiple sessions.

**Comment by coderbyheart** [comment]
I've added Sentry to track issues in prod

**Comment by j19sch** [comment]
> Tested on OS X 14.2 and Firefox 121 and could add multiple sessions.

Can't replicate anymore on OS X either.

**Comment by j19sch** [comment]
> Could you share the error log from the console when you reproduce it?

Here it is. Only error in there is about failing to parse `-webkit-text-size-adjust`.

[console-export-2023-12-24_14-52-37.txt](https://github.com/coderbyheart/localschedule/files/13761992/console-export-2023-12-24_14-52-37.txt)

**Comment by j19sch** [comment]
I can't reproduce it on Firefox 121.0 (64-bit) mozilla-flatpak 1.0, while I still can reproduce it on Firefox 119.0 (64-bit) canonical-002 1.0.

**Comment by j19sch** [comment]
Forced the snap Firefox to update from 119.0 to 121.0 and I can no longer reproduce the issue.

So I'll close this issue, since it does seem like it was some Firefox issue that was solved in the mean time. Thank you for looking into it!

**Comment by coderbyheart** [comment]
> > Could you share the error log from the console when you reproduce it?
> 
> Here it is. Only error in there is about failing to parse `-webkit-text-size-adjust`.
> 
> [console-export-2023-12-24_14-52-37.txt](https://github.com/coderbyheart/localschedule/files/13761992/console-export-2023-12-24_14-52-37.txt)

And that is a CSS error. That would not cause the page to reload.

I suspect there may be some text that you used that caused the reload, because all the data is encoded in the URL.
