### ISSUE TITLE
em dash in session name leads to Uncaught DOMException: String contains an invalid character

### ISSUE THREAD

**Issue by j19sch** [coderbyheart/localschedule#17]
It's possible to put an em dash `–` in a Session's name, but then you can't save the schedule.

**Steps to reproduce**
1. Input an em dash `–` as a Session's name.
2. Click the green plus icon.
3. Click the open lock icon in the top-left.

**Result**
- Lock icon remain open, page remains in edit mode.
- Browser console shows a `Uncaught DOMException: String contains an invalid character` error

```
Uncaught DOMException: String contains an invalid character bundle.js:2
    onClick https://localschedule.netlify.app/bundle.js?6798957bbfda9b9200f0becc03307fd0657706fe:2
    React 12
        ki
        ji
        mi
        lf
        wi
        Kd
        pc
        Wf
        <anonymous>
        uf
        Qd
        sc
    bind_applyFunctionN self-hosted:1373
    sc self-hosted:1336
    React 4
        unstable_runWithPriority
        Da
        <anonymous>
        Ei
    bind_applyFunctionN self-hosted:1373
    Ei self-hosted:1336
```

**Comment by coderbyheart** [comment]
Nice find, will fix!

**Comment by coderbyheart** [comment]
Fixed: https://localschedule.netlify.app/#v2%3A%7B%22name%22%3A%22ExampleConf%22%2C%22day%22%3A%222021-07-20%22%2C%22tz%22%3A%22Europe%2FOslo%22%2C%22sessions%22%3A%7B%221930%22%3A%22%F0%9F%98%81%22%2C%221945%22%3A%22%E2%80%93%22%7D%7D
