### ISSUE TITLE
Day count seems to be incorrect in some cases.

### ISSUE THREAD

**Issue by cwortel** [coderbyheart/localschedule#6]
We've created the following schedule for TestCraftCamp.nl https://localschedule.netlify.app/#eyJuYW1lIjoiVGVzdENyYWZ0Q2FtcCIsImRheSI6IjIwMjAtMDktMTkiLCJ0eiI6IkV1cm9wZS9BbXN0ZXJkYW0iLCJzZXNzaW9ucyI6eyI5MDAiOiJXYWxrIGluICYgU2hhcmVkIEJyZWFrZmFzdCIsIjkxNSI6Ik1hcmtldHBsYWNlIChtb3JuaW5nIHNlc3Npb25zKSIsIjEwMDAiOiJSb3VuZCAxIiwiMTA0NSI6IkJyZWFrIiwiMTEwMCI6IlJvdW5kIDIiLCIxMTQ1IjoiQnJlYWsiLCIxMjAwIjoiUm91bmQgMyIsIjEyNDUiOiJMdW5jaCIsIjEzMzAiOiJNYXJrZXRwbGFjZSAoYWZ0ZXJub29uIHNlc3Npb25zKSIsIjE0MDAiOiJSb3VuZCA0IiwiMTQ0NSI6IkJyZWFrIiwiMTUwMCI6IlJvdW5kIDUiLCIxNTQ1IjoiQnJlYWsiLCIxNjAwIjoiUm91bmQgNiIsIjE2NDUiOiJSZXRyb3NwZWN0aXZlICYgQ2xvc2luZyJ9fQ%3D%3D
Most of it seems to work fine, but there is something awkward with the day count; Starts in ... days. The startdate for the whole table is the same, but in my case the first two lines say 4 days and the rest says 5 days. 
I have a feeling it might have something to do with the moment it uses as a startpoint in relation to the current time. I did not wait for the next interval to check yet. Short calculation gives me the believe It rounds off at half days
![image](https://user-images.githubusercontent.com/703721/93129949-19860500-f6d2-11ea-91ca-98da45d32da6.png)

Joep offers to fix it as an exercise during the conference ;)

**Comment by coderbyheart** [comment]
uh, nice bug. I'll have a look at it.

Thank you for the report!
